# -*- coding: utf-8 -*-
"""Funcoes_felipe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lXhfDr4M7wBKs4bdofdq36fq3NIgD4jC
"""

#1
def temperatura(F):
  C = (F -32) * 5/9

  return C

temperatura(86)

#2
import math

def triangulo(a,b):
  h = math.sqrt(a**2 + b**2)

  return h

triangulo(10,25)

#3
def media_nota(a,b):
  media = (a + b) / 2
  if media >= 6:
    return("Parabéns! Você foi aprovado!")
  
media_nota(5,8)

#4
def pesoideal(sexo,h):
  if sexo == 1:
    imc = (72.7 * h) - 58
  elif sexo == 2:
    imc = (62.1 * h) - 44.7

  return imc

pesoideal(2,1.65)

#6
def soma_intervalos(n1,n2):
  n1 += 1
  soma = 0
  for i in range(n1,n2):
    soma += i
  return soma

soma_intervalos(1,5)

#7
def mes(numero):
  meses = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]
  pos = numero - 1
  if numero == 0 or numero > 12:
    return("Esse mês não existe!")
  else:
    return meses[pos] 

mes(11)