# -*- coding: utf-8 -*-
"""Lista_Vetores_Matrizes- Felipe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xciCW59_S5ULNUkohksfo66GVaPFHKSk
"""

#1

number = 0
for i in range(100):
  lista.append(number)
  number += 1
print(lista)

#2

notas = []
nota_somada = int(0)
pos = int(0)
qtd_provas = int(input("Quantas notas serão adicionadas?"))

for i in range(qtd_provas):
  provas = float(input("Digite a nota:"))
  notas.append(provas) 

for i in notas:
  nota_somada += i


qtd_notas = len(notas)
nota = nota_somada / qtd_notas
print(nota)

#3

nota = []
nota_somada = int(0)
pos = int(0)
valores_acima = int(0)
qtd_provas = int(input("Quantas notas serão adicionadas?"))

for i in range(qtd_provas):
  provas = float(input("Digite a nota:"))
  nota.append(provas) 

for i in nota:
  nota_somada += i


qtd_notas = len(nota)
notas = nota_somada / qtd_notas

print(notas)
print(nota)

for i in nota:
  if i > notas:
    valores_acima += 1
  
print(valores_acima, "prova(as) com nota acima de sua média!")

#4

nota = []
nota_somada = int(0)
pos = int(0)
notas_baixas = int(0)
maior_nota = int(0)
menor_nota = int(10)

for i in range(30):
  provas = float(input("Digite a nota:"))
  nota.append(provas) 

for i in nota:
  nota_somada += i


qtd_notas = len(nota)
notas = nota_somada / qtd_notas

print(notas)
print(nota)

for i in nota:
  if i < notas:
    notas_baixas += 1
  if i > maior_nota:
    maior_nota = i
  if i < menor_nota:
    menor_nota = i
  
print(notas_baixas, "prova(as) com nota abaixo da média!")
print("A maior nota foi", maior_nota)
print("A menor nota foi", menor_nota)

#5

import random
numeros = []
posicoes_numero = []
pos = int(0)
for i in range(100):
  num = random.randint(1,30)
  numeros.append(num)

print(numeros)

for i in numeros:
  if i == 30:
    posicoes_numero.append(pos)
  pos += 1
    
print("Foi encontrado o número 30 nas posições", posicoes_numero)

#6

import random
vetor = []
soma = int(0)
for i in range(100):
  num = random.uniform(0, 1000)
  vetor.append(num)

for i in vetor:
  soma += i

print(vetor)
print(soma)

#7

import random
vetor = []
for i in range(200):
  num = random.randint(0, 1000)
  vetor.append(num)

print(vetor)
print(vetor[::-1])

#9

import random

lista1 = []
lista2 = []
nova_lista = []

for i in range(25):
  num = random.randint(1,100)
  lista1.append(num)
print(lista1)

for i in range(25):
  num = random.randint(1,100)
  lista2.append(num)
print(lista2)

nova_lista = lista1 + lista2

print(nova_lista)

#11

import random

vetor1 = []
vetor2 = []

for i in range(10):
  num = random.randint(0, 20)
  vetor1.append(num)
  if num % 2 == 0:
    vetor2.append(num * 3)
  else:
    vetor2.append(num * 2)

print(vetor1)
print(vetor2)

#15

import random

vetor = []

for i in range(20):
  num = random.randint(0,100)
  vetor.append(num)

vetor.sort(key=int)

print(vetor)