# -*- coding: utf-8 -*-
"""Repetição_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLALstLmkpcgnLQPwg4IlpScNg8ctd02
"""

negativos = []
soma_positivos = int(0)
contador = int(0)

numeros = [1,5,-6,8,10,-8,-54,10,15,3,-3,12,7,4,-4,-13,-17,14,-21,22]
for i in numeros:
  if i < 0:
    negativos.append(i)
  elif i > 0:
    soma_positivos += i
    contador += 1

calculo = soma_positivos / contador
print("Os números negativos são:", negativos)
print("A média dos positivos é",calculo)

from time import sleep
numeros = [1,5,6,9,10,8,54,11,15,3,36,12,7,4,48]
for i in numeros:
  if i % 2 == 0:
    print(i, "é par!")
  elif i % 2 != 0:
    print(i, "é impar!")
  time.sleep(0.5)

numeros = [0, 1,5,6,9,10,8,54,11,15,3,36,12,7,4,48]
maior_numero = 0

for i in numeros:
  if i > maior_numero:
    maior_numero = i

menor_numero = maior_numero

for i in numeros:
  if i < menor_numero and i != 0:
    menor_numero = i

print("O maior número é", maior_numero)
print("O menor número é", menor_numero)

numeros = []
numero_gerador = int(1)

while numero_gerador < 101:
  numeros.append(numero_gerador)
  numero_gerador += 1

soma_pares = int(0)
soma_impares = int(0)

for i in numeros:
  if i % 2 == 0:
    soma_pares += i
  elif i % 2 != 0:
    soma_impares += i

print("A soma dos números pares é", soma_pares)
print("A soma dos números impares é", soma_impares)

alturas = [1.70,1.80,1.95,1.45,1.65,1.6,1.56,1.69,2.01,1.77,1.74,1.78,1.79,1.90,1.75,2.05,1.64,1.60,1.68,1.71,1.81]
qtd_pessoas = int(0)
soma_alturas = int(0)
for i in alturas:
  soma_alturas += i
  qtd_pessoas += 1

print("A média aritmética das alturas é de", round(soma_alturas / qtd_pessoas, 2), "m")

numeros = [1,5,-6,8,10,-8,-54,10,15,3,-3,12,7,4,-4,-13,-17,14,-21,22]
negativos = int(0)
for i in numeros:
  if i < 0:
    negativos += 1
print("Há", negativos, "valores negativos!")

from time import sleep
tinta_restante = int(input("Quantos % de tinta a caneta possui?"))
while tinta_restante > 0:
  print("Enquanto tem tinta a caneta escreve...")
  tinta_restante -= 2
  time.sleep(0.25)
print("Ops, a tinta acabou!")