# -*- coding: utf-8 -*-
"""Revisão Python - Estrutura de Decisão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I9xunx3a6z-Ot_SEqfSJQl9jkhtBIa1U
"""

ladoa = int(input("Lado a: "))
ladob= int(input("Lado b: "))
ladoc = int(input("Lado c: "))

if ladoa == ladob == ladoc:
	print("Triângulo Equilatero")
elif ladoa == ladob or ladoa == ladoc or ladob == ladoc:
	print("Triângulo Isósceles")
elif ladoa != ladob != ladoc:
	print("Triângulo Escaleno")
else:
  print("Não forma um triângulo!")

ano = int(input('Digite algum Ano: '))
if (ano % 4 == 0 and ano % 100 != 0) or ( ano % 400 == 0):
    print('Esse ano é Bissexto')
else:
    print('Esse ano não é bissexto')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
numero3 = int(input("Digite o terceiro número:"))

if numero1 >  numero2 and numero1 > numero3:
  print("O maior número é o primeiro!")
elif numero2 > numero1 and numero2 > numero3:
  print("O maior número é o segundo!")
elif numero3 > numero1 and numero3 > numero2:
  print("O maior número é o terceiro!")
else:
  print("Ambos os números são iguais!")

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
numero3 = int(input("Digite o terceiro número:"))

maior_numero = ""
menor_numero = ""

if numero1 >  numero2 and numero1 > numero3:
  print("O maior número é o primeiro!")
elif numero2 > numero1 and numero2 > numero3:
  print("O maior número é o segundo!")
elif numero3 > numero1 and numero3 > numero2:
  print("O maior número é o terceiro!")

if numero1 < numero2 and numero1 < numero3:
  print("O menor número é o primeiro")
elif numero2 < numero1 and numero2 < numero3:
  print("O menor número é o segundo!")
elif numero3 < numero1 and numero3 < numero2:
  print("O menor número é o terceiro!")
else:
  print("Ambos os números são iguais!")

metros_pintado = float(input("Quantos metros quadrados serão pintados?"))

litros_usados = metros_pintado / 3
preco_lata = 80
capacidade = 18

if litros_usados % 54 != 0:
  latas_usadas = int(litros_usados / capacidade)
if metros_pintado <= 54:
  latas_usadas = 1
else:
  latas_usadas = int((litros_usados / capacidade) + 1)

preco_a_pagar = latas_usadas * preco_lata


print("foram usadas", latas_usadas, "latas")
print("O preço a se pagar será de R$ ", preco_a_pagar)